export const STRINGS = {
  allGenres: 'All Genres',
  allDecades: 'All Decades',
  releaseYear: 'Release Year',
  rating: 'Rating',
  trackName: 'Track Name',
  artist: 'Artist',
  albumName: 'Album Name',
  genre: 'Genre',
  releaseYearLabel: 'Release Year',
  ratingLabel: 'Rating',
  loadMore: 'Load More',
  loading: 'Loading...',
  searchPlaceholder: 'Search by track, artist, or album...',
  filters: 'Filters',
  trackList: 'Track list',
  viewDetails: (track: string, artist: string) => `View details for ${track} by ${artist}`,
  details: {
    artist: 'Artist',
    album: 'Album',
    genre: 'Genre',
    releaseYear: 'Release Year',
    releaseDate: 'Release Date',
    rating: 'Rating',
    trackName: 'Track Name',
  },
};
